# -*- coding: utf-8 -*-
"""debate_banoAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyL-xDXg8NqZPfz8WHM0-hRuQCuI8yXA
"""

! pip install langchain-community langchain_huggingface  langgraph

import os
from typing import TypedDict, Annotated
from langgraph.graph import StateGraph
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
import operator

#  HuggingFace API
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACEHUB_ACCESS_TOKEM2")

# Initialize LLM models
llm = HuggingFaceEndpoint(
    repo_id="meta-llama/Meta-Llama-3-8B-Instruct",
    task="text-generation",
    temperature=0.7,
    huggingfacehub_api_token="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"
)

llm1 = HuggingFaceEndpoint(
    repo_id="meta-llama/Meta-Llama-3-8B-Instruct",
    task="text-generation",
    temperature=0.7,
    huggingfacehub_api_token="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"
)

# Create chat models for both players and judge
chat_model = ChatHuggingFace(llm=llm)
chat_model1 = ChatHuggingFace(llm=llm1)

class agent(TypedDict):
    topic: str
    player1_arguments: Annotated[list, operator.add]  # Can handle concurrent updates
    player2_arguments: Annotated[list, operator.add]  # Can handle concurrent updates
    judgment: str

def get_input(state: agent) -> agent:
    """Get debate topic from user"""
    state['topic'] = input("🎯 Enter debate topic: ")
    print("\n" + "="*80)
    print("🤖 Starting Debate - Generating Arguments...")
    print("="*80 + "\n")
    return state

def player1_affirmative(state: agent) -> agent:
    """Player 1: Generate 7 arguments FOR the topic"""
    arguments = []

    print("✅ PLAYER 1 (AFFIRMATIVE - Supporting the topic)")
    print("-" * 80)

    for i in range(1, 8):
        prompt = f"""You are a skilled debater arguing FOR the topic: "{state['topic']}"

Generate argument number {i} supporting this position. Make it strong, logical, and persuasive. Keep it concise (2-3 sentences)."""

        response = chat_model.invoke(prompt)
        argument = response.content if hasattr(response, 'content') else str(response)
        arguments.append(argument)
        print(f"\n[Argument {i}] {argument}")

    print("\n" + "="*80 + "\n")
    return {"player1_arguments": arguments}

def player2_negative(state: agent) -> agent:
    """Player 2: Generate 7 arguments AGAINST the topic"""
    arguments = []

    print("❌ PLAYER 2 (NEGATIVE - Opposing the topic)")
    print("-" * 80)

    for i in range(1, 8):
        prompt = f"""You are a skilled debater arguing AGAINST the topic: "{state['topic']}"

Generate argument number {i} opposing this position. Make it strong, logical, and persuasive. Keep it concise (2-3 sentences)."""

        response = chat_model1.invoke(prompt)
        argument = response.content if hasattr(response, 'content') else str(response)
        arguments.append(argument)
        print(f"\n[Argument {i}] {argument}")

    print("\n" + "="*80 + "\n")
    return {"player2_arguments": arguments}

def judge_debate(state: agent) -> agent:
    """Evaluate both sides and determine winner"""

    print("⚖️  JUDGE IS EVALUATING THE DEBATE...")
    print("="*80 + "\n")

    # Format arguments with numbers for the judge
    player1_formatted = "\n".join([f"Argument {i+1}: {arg}" for i, arg in enumerate(state['player1_arguments'])])
    player2_formatted = "\n".join([f"Argument {i+1}: {arg}" for i, arg in enumerate(state['player2_arguments'])])

    prompt = f"""You are an impartial debate judge. Evaluate the following debate:

TOPIC: "{state['topic']}"

AFFIRMATIVE SIDE (Player 1 - Supporting):
{player1_formatted}

NEGATIVE SIDE (Player 2 - Opposing):
{player2_formatted}

Provide your judgment with:
1. Brief analysis of each side's strongest points (mention specific argument numbers)
2. Which side presented more compelling arguments overall
3. Final verdict: State clearly "Winner: Player 1" or "Winner: Player 2"
4. Brief reasoning (2-3 sentences)

Be objective and fair."""

    response = chat_model.invoke(prompt)
    state['judgment'] = response.content if hasattr(response, 'content') else str(response)
    return state

# Build the debate graph
graph = StateGraph(agent)

# Add nodes
graph.add_node("input", get_input)
graph.add_node("player1", player1_affirmative)
graph.add_node("player2", player2_negative)
graph.add_node("judge", judge_debate)

# Define edges - parallel execution for both players
graph.add_edge("input", "player1")
graph.add_edge("input", "player2")
graph.add_edge("player1", "judge")
graph.add_edge("player2", "judge")

# Set entry and finish points
graph.set_entry_point("input")
graph.set_finish_point("judge")

# Compile the graph
debate_app = graph.compile()

# Run the debate
if __name__ == "__main__":
    print("\n" + "="*80)
    print("🎭 AI DEBATE SYSTEM - LLaMA 3 vs LLaMA 3")
    print("="*80 + "\n")

    # Initialize state
    initial_state = {
        "topic": "",
        "player1_arguments": [],
        "player2_arguments": [],
        "judgment": ""
    }

    # Run the debate
    result = debate_app.invoke(initial_state)

    # Print final summary
    print("\n" + "="*80)
    print("📊 FINAL DEBATE SUMMARY")
    print("="*80)
    print(f"\n📌 Topic: {result['topic']}\n")

    print("✅ PLAYER 1 (AFFIRMATIVE):")
    print("-" * 80)
    for i, arg in enumerate(result['player1_arguments'], 1):
        print(f"[{i}] {arg}\n")

    print("\n❌ PLAYER 2 (NEGATIVE):")
    print("-" * 80)
    for i, arg in enumerate(result['player2_arguments'], 1):
        print(f"[{i}] {arg}\n")

    print("\n⚖️ JUDGE'S FINAL VERDICT:")
    print("="*80)
    print(result['judgment'])
    print("="*80 + "\n")

    print("✨ Debate Complete! ✨\n")

